<p>{'Dear'|i18n('translationmanagement/mail')} {$mail.recipient|wash('email')},</p>
<p>{'a new collaboration from'|i18n('translationmanagement/mail')} {$mail.sender|wash('email')} {'is waiting for you here'|i18n('translationmanagement/mail')}: <a href="{concat($protocol, $mail.url, '/' , $admin_siteaccess ,$mail.link)}">{concat($protocol, $mail.url, '/' , $admin_siteaccess ,$mail.link)}</a></p>
<p>{'Please cover until'|i18n('translationmanagement/mail')} {$mail.deadline|l10n('date')}.</p>
<hr />
<p>{'Translation details'|i18n('translationmanagement/mail')} {if and(is_set($mail.sourcelang), $mail.sourcelang|ne(''))}({'from'|i18n('translationmanagement/mail')} {$mail.sourcelang} {'to'|i18n('translationmanagement/mail')} {$mail.tolang}){/if}:</p>
{foreach $mail.objectnames as $objectname max 50}
    <p><a href="{concat($protocol, $mail.url, '/' , $admin_siteaccess, '/', $objectname.main_node.url_alias)}">{$objectname.name|wash()}</a></p>
{/foreach}
<hr />
<p>{'Generated by'|i18n('translationmanagement/mail')} {$mail.sender} {'translation system'|i18n('translationmanagement/mail')}.</p>