{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $errors = $collab_item.content.errors}

{if $errors}
    {foreach $errors as $error}
        <div class="message-error">
            <h2>{$error|wash}</h2>
        </div>
    {/foreach}
{/if}

{def $process_id = $collab_item.content.process_id
     $languages = $collab_item.content.languages
     $all_languages=fetch('content','prioritized_languages', hash( ) )
     $process = $collab_item.content.process
     $deadline = $collab_item.content.deadline
     $objects=fetch( 'tm', 'objects_by_process_id', hash( 'process_id', $collab_item.data_int1 ) )
     $message_limit=2
     $message_offset=0
     $current_participant=fetch("collaboration","participant",hash("item_id",$collab_item.id))
     $participant_list=fetch("tm","participant_map",hash("item_id",$collab_item.id))
     $message_list=fetch("collaboration","message_list",hash("item_id",$collab_item.id,"limit",$message_limit,"offset",$message_offset))
     $text = ""
     $version_number = ""
     $tm = ""
     $row_count = 0
     $version = ""
     $tm_collab = ""
     $tm_work = ""
     $redirectme=ezhttp('LastAccessesURI', 'session')
     $languages_table = ""
}
<script language="JavaScript" type="text/javascript">
    function confirmDiscard( question )
    {ldelim}
        // Ask user if she really wants do it, return this to the handler.
        return confirm( question );
    {rdelim}
</script>

<div class="context-block">
    {* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
    <h1 class="context-title">{"Translation"|i18n('design/admin/collaboration/handler/view/full/ezapprove')}</h1>
    {* DESIGN: Mainline *}<div class="header-mainline"></div>
    {* DESIGN: Header END *}</div></div></div></div></div></div>
    {* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">
    <table class="list">
        <tr>
            <th scope="row">{'Deadline'|i18n('extension/tm')}</th>
            <td>
                <div class="block">
                    <div class="element">
                        <label>{'Day'|i18n('extension/tm')} <input type="text" value="{$deadline.day}" name="deadline_day" size="2" maxlength="2" disabled="disabled" /></label>
                    </div>
                    <div class="element">
                        <label>{'Month'|i18n('extension/tm')} <input type="text" value="{$deadline.month}" name="deadline_month"  size="2" maxlength="2" disabled="disabled" /></label>
                    </div>
                    <div class="element">
                        <label>{'Year'|i18n('extension/tm')} <input type="text" value="{$deadline.year}" name="deadline_year"  size="4" maxlength="4" disabled="disabled" /></label>
                    </div>
                </div>
                <div class="break"></div>
            </td>
        </tr>
        <tr>
            <th scope="row">{'Collaboration ID'|i18n('extension/tm')}</th>
            <td>{$collab_item.id}</td>
        </tr>
        <tr>
            <th scope="row">{'Process ID'|i18n('extension/tm')}</th>
            <td>{$process_id}</td>
        </tr>
        <tr>
            <th scope="row">{'Source Language'|i18n('extension/tm')}</th>
            <td>{$collab_item.content.source.name}</td>
        </tr>
    </table>
    {* DESIGN: Content END *}</div></div></div>
</div>

<div class="context-attributes">
    {switch match=$collab_item.data_int3}
        {case in=array(1)}
            {if $objects|count|eq(1)}
                <p>{"A content object awaits translation before it can be published."|i18n('extension/tm')}</p>
            {else}
                <p>{"A content object collection awaits translation before it can be published."|i18n('extension/tm')}</p>
            {/if}
        {/case}
        {case in=array(6)}
            {if $objects|count|eq(1)}
                <p>{"A content object awaits approval before it can be published."|i18n('extension/tm')}</p>
            {else}
                <p>{"A content object collection awaits approval before it can be published."|i18n('extension/tm')}</p>
            {/if}
        {/case}
        {case match=8}
           <p>{"Translation process was approved for publishing"|i18n('design/standard/collaboration')}</p>
        {/case}
        {case match=9}
           <p>{"Translation process was rejected"|i18n('design/standard/collaboration')}</p>
        {/case}
        {case match=10}
           <p>{"Translation process is waiting for publishing"|i18n('design/standard/collaboration')}</p>
        {/case}
    {/switch}

    <ul>
        {if and( $collab_item.is_creator,  array(7,8)|contains( $collab_item.data_int3 )|not )}
            <li>{'If you want to leave a message for all current invited participants, you may insert it here and press "Add comment" for submission.'|i18n('extension/tm')}</li>
            <li>{'"Approve" will publish the object with all translations that have been received.'|i18n('extension/tm')}</li>
            <li>{'Pressing "Discard draft" will abandon this pending draft, including your modified source version and all translations that might have been received.'|i18n('extension/tm')}</li>
        {/if}
        {if and( array(1,2,4)|contains($collab_item.data_int3), $current_participant.participant_role|eq(1030) )}
            <li>{"The content objects need your translation before it can be published."|i18n('design/admin/collaboration/handler/view/full/ezapprove')}</li>
        {/if}
        {if and( array(6)|contains($collab_item.data_int3), $current_participant.participant_role|eq(1032) )}
            <li>{"The content object %1 needs your confirmation before it can be published."|i18n('design/admin/collaboration/handler/view/full/ezapprove',,array($contentobject_link))}</li>
        {/if}
        {switch match=$collab_item.data_int3}
            {case in=array(1,6,10)}
            {/case}
            {case in=array(2,3)}
                {if $collab_item.is_creator}
                    {if and( is_set( $contentobject_link ),$contentobject_link )}
                        <p>{"The content objects were not accepted but is available as a draft again."|i18n('design/admin/collaboration/handler/view/full/ezapprove',,array($contentobject_link))}</p>
                    {else}
                        <p>{"The content objects [deleted] were not accepted but are available as a draft again."|i18n('design/admin/collaboration/handler/view/full/ezapprove',,array($collab_item.content.content_object_id))}</p>
                    {/if}
                    {if $content_version|null()|not()}
                      <p>{"You may reedit the draft and publish it, in which case an approval is required again."|i18n('design/admin/collaboration/handler/view/full/ezapprove')}</p>
                      <p><a href={concat("content/edit/",$content_version.contentobject_id)|ezurl}>{"Edit the object"|i18n('design/admin/collaboration/handler/view/full/ezapprove')}</a></p>
                    {/if}
                  {else}
                    {if and( is_set( $contentobject_link ),$contentobject_link )}
                        <p>{"The content objects were not accepted but will be available as a draft for the author."|i18n('design/admin/collaboration/handler/view/full/ezapprove',,array($contentobject_link))}</p>
                    {else}
                        <p>{"The content objects [deleted] were not accepted but will be available as a draft for the author."|i18n('design/admin/collaboration/handler/view/full/ezapprove',,array($collab_item.content.content_object_id))}</p>
                    {/if}
                    <p>{"The author can reedit the draft and publish it again, in which a new approval item is made."|i18n('design/admin/collaboration/handler/view/full/ezapprove')}</p>
                  {/if}
            {/case}
        {/switch}
        {if array(7,8)|contains($collab_item.data_int3)}
            <li>{"The process is completed at this stage."|i18n('design/admin/collaboration/handler/view/full/ezapprove',,array($contentobject_link))}</li>
        {/if}
    </ul>
    <form name="editform" method="post" action={"collaboration/action/"|ezurl}  enctype="multipart/form-data">
        {if array(1,2,3,4,6,9,10)|contains($collab_item.data_int3)}
            <label>{"Comment"|i18n('design/admin/collaboration/handler/view/full/ezapprove')}:</label>
            <textarea class="box" name="Collaboration_ApproveComment" cols="40" rows="5"></textarea>
        {/if}
        <input type="hidden" name="CollaborationActionCustom" value="custom" />
        <input type="hidden" name="CollaborationTypeIdentifier" value="translation" />
        <input type="hidden" name="CollaborationItemID" value="{$collab_item.id}" />
        {def $access=fetch( 'user', 'has_access_to',
                            hash( 'module',   'tm',
                                  'function', 'administrate' ) )}

        {if and( array(7,8,9,10)|contains( $collab_item.data_int3 )|not,$collab_item.is_creator)}

            <input class="button" type="submit" name="CollaborationAction_Accept" value="{'Accept Collaboration'|i18n('design/admin/collaboration/handler/view/full/ezapprove')}" />
            <input class="button" type="submit" name="CollaborationAction_Deny" value="{'Abort Collaboration'|i18n('design/admin/collaboration/handler/view/full/ezapprove')}" onclick="return confirmDiscard( 'Are you sure you want to discard the draft?' );" title="Discard the draft that is being translated. This will also remove all new translations to the draft." />
        {/if}
        
        {if and( array(10)|contains( $collab_item.data_int3 ),$collab_item.is_creator)}
            <input class="button" type="submit" name="CollaborationAction_Accept" value="{'Accept Collaboration'|i18n('design/admin/collaboration/handler/view/full/ezapprove')}" />
            <input class="button" type="submit" name="CollaborationAction_Deny" value="{'Abort Collaboration'|i18n('design/admin/collaboration/handler/view/full/ezapprove')}" onclick="return confirmDiscard( 'Are you sure you want to discard the draft?' );" title="Discard the draft that is being translated. This will also remove all new translations to the draft." />
        {/if}        
        {if array(1,2,3,4,6,9,10)|contains($collab_item.data_int3)}
            <input class="button" type="submit" name="CollaborationAction_Comment" value="{'Add Comment'|i18n('design/admin/collaboration/handler/view/full/ezapprove')}" />
        {/if}
    </form>
    {if $languages|count|gt(0)}
        {if array(7,8)|contains($collab_item.data_int3)|not}
            <div class="button-right">
                <form name="download" method="post" action={"tm/downloadxml"|ezurl}>
                    <input type="hidden" name="source" value="{$translation.locale}" />
                    <input type="hidden" name="process" value="{$process_id}" />
                    <select name="target">
                        {foreach $languages as $key => $language}
                            <option value="{$language.locale}">{$language.name}</option>
                        {/foreach}
                    </select>
                    <input class="button" type="submit" name="Download" value="Download" title="Download your translation source" />
                </form>
            </div>
            <div class="break"></div>
        {if array(10)|contains($collab_item.data_int3)|not}
            <div class="button-right">
                <form method="post" action={"collaboration/action/"|ezurl}  enctype="multipart/form-data">
                    <input type="hidden" name="CollaborationActionCustom" value="custom" />
                    <input type="hidden" name="CollaborationTypeIdentifier" value="translation" />
                    <input type="hidden" name="CollaborationItemID" value="{$collab_item.id}" />
                    <div class="break"></div>
                    <label>Translation file: </label>
                    <input type="file" name="file" accept="text/*" />
                    <input class="button" type="submit" name="CollaborationAction_Upload" value="    Upload   " />
                </form>
            </div>
        {/if}
        {/if}
    {/if}
</div>

<div class="break"></div>

<div class="context-block">
    {* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
    <h2 class="context-title">{"Participants"|i18n('design/admin/collaboration/handler/view/full/ezapprove')}</h2>
    {* DESIGN: Mainline *}<div class="header-subline"></div>
    {* DESIGN: Header END *}</div></div></div></div></div></div>
    {* DESIGN: Content START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-bl"><div class="box-br"><div class="box-content">
    <table class="list">
        {foreach $participant_list as $role}
            <tr>
                <th class="tight">{$role.role|wash}</th>
                   <td>
                   {foreach $role.items as $participant}
                       <p><a href={$participant.participant.contentobject.main_node.url_alias|ezurl()}>{$participant.participant.contentobject.name|wash}</a></p>
                   {/foreach}
                   </td>
               </tr>
        {/foreach}
    </table>
    {* DESIGN: Content END *}</div></div></div></div></div></div>
</div>

{if $message_list}
    <div class="context-block">
        {* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
        <h2 id="messages" class="context-title">{"Messages"|i18n('design/admin/collaboration/handler/view/full/ezapprove')}</h2>
        {* DESIGN: Mainline *}<div class="header-subline"></div>
        {* DESIGN: Header END *}</div></div></div></div></div></div>
        {* DESIGN: Content START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-bl"><div class="box-br"><div class="box-content">
        <table class="special" cellspacing="0">
            {foreach $message_list as $message sequence array( 'bglight', 'bgdark' ) as $sequence}
                {collaboration_simple_message_view view=element sequence=$sequence is_read=$current_participant.last_read|gt($message.modified) item_link=$message collaboration_message=$message.simple_message}
              {/foreach}
        </table>
        {* DESIGN: Content END *}</div></div></div></div></div></div>
    </div>
{/if}

{if $objects}
    <div class="context-block">
    {* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
    <h2 id="messages" class="context-title">{"Objects"|i18n('design/admin/collaboration/handler/view/full/ezapprove')}</h2>
    {* DESIGN: Mainline *}<div class="header-subline"></div>
    {* DESIGN: Header END *}</div></div></div></div></div></div>
    {* DESIGN: Content START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-bl"><div class="box-br"><div class="box-content">
    <table class="list" cellspacing="0">
        <tr>
            <th class="col">{'Object Information'|i18n('extension/tm')}</th>
            <th class="col">{'Languages'|i18n('extension/tm')}</th>
            <th class="col">{'Assigned'|i18n('extension/tm')}</th>
            <th class="col">{'Checker'|i18n('extension/tm')}</th>
            <th class="col">{'Status'|i18n('extension/tm')}</th>
            <th class="col">{'Actions'|i18n('extension/tm')}</th>
        </tr>
        {foreach $objects as $object sequence array( 'bglight', 'bgdark' ) as $sequence}
            {set $version_number = $process.parameter_list.versions.[$object.id]
                 $tm_work = fetch('tm','work_object_status', hash( process_id, $process.id, contentobject_id, $object.id, version, $version_number ) )
                 $tm_collab = fetch('tm','collaboration_item', hash( contentobject_id, $object.id, version, $version_number ))
                 $version=fetch( 'content', 'version', hash( 'object_id',  $object.id, 'version_id',  $version_number ) )
                 $languages_table = fetch('tm','available_languages', hash( version, $version ) )
             }

            {foreach $languages_table as $key => $translation}
                {set $tm = fetch('tm','status', hash( contentobject_id, $object.id, version, $version_number, language, $translation.locale ) )}
                {if and( $tm, $tm.translated_from|ne( $translation.locale ) )}
                    {set $row_count = inc( $row_count )}
                {/if}
            {/foreach}

            {if $draft.initial_language.locale|eq($tm_collab.content.source.locale)}
                {set $text=concat(  'content/versionview/', $object.id, '/', $version_number, '/', $collab_item.content.source.locale )|ezurl(no)}
            {else}
                {set $text=concat(  'content/versionview/', $object.id, '/', $object.current_version, '/', $collab_item.content.source.locale )|ezurl(no)}
            {/if}
            {def $counter = 0}           
            <tr class="{$sequence}">
                <td rowspan="{$row_count}">
                    <a href={$object.main_node.url_alias|ezurl()}>{$object.name}</a> ( {if $tm_work}<span class="tm-completed">{'completed'|i18n('extension/tm')}</span>{else}<span class="tm-not-completed">{'not completed'|i18n('extension/tm')}</span>{/if} )
                    <input class="button" type="button" onclick="window.open( '{$text}' ,'Win','resizeable=yes,scrollbars=yes');" name="View" value="View" title="{'Preview your content'|i18n('extension/tm')}" />
                </td>
            {foreach $languages_table as $key => $translation sequence array("bgdark", "bglight") as $sequence}
                {set $tm = fetch('tm','status', hash( contentobject_id, $object.id, version, $version_number, language, $translation.locale ) )}
                {if and( $tm, $tm.translated_from|ne($translation.locale) )}
					{if and( $row_count|gt( 1 ), $counter|ne( 0 ) )}
						<tr>         
					{/if}
					{set $counter = $counter|inc()}
					<td>{$translation.name}</td>
                    <td>{node_view_gui view=text_linked content_node=$tm.user.contentobject.main_node}</td>
                    <td>{node_view_gui view=text_linked content_node=$tm.approver.contentobject.main_node}</td>
                    <td>{$tm.status_name}</td>
                    <td>
                        <div class="block">
                            <div class="element">
								{set $text=concat(  'content/versionview/', $object.id, '/', $version_number, '/', $tm.language )|ezurl(no)}								
                                <input class="button" type="button" onclick="window.open( '{$text}' ,'Win','resizeable=yes,scrollbars=yes');" name="View" value="View" title="Preview your content" />
                            </div>
                            {if $tm.status|eq( 4 )}
                            <div class="element">
                                <form method="post" action={"collaboration/action/"|ezurl}  enctype="multipart/form-data">
                                    <input name="CollaborationActionCustom" type="hidden"  value="custom" />
                                    <input name="CollaborationTypeIdentifier" type="hidden" value="translation" />
                                    <input name="CollaborationItemID" type="hidden" value="{$collab_item.id}" />
                                    <input name="ObjectID" type="hidden" value="{$tm.contentobject_id}" />
                                    <input name="VersionID" type="hidden" value="{$tm.contentobject_version}" /> 
                                    <input name="Target" type="hidden" value="{$tm.language}" />
                                    <input class="button" type="submit" name="CollaborationAction_Confirm" value="{'Confirm'|i18n('extension/tm')}" title="{'Confirm your upload'|i18n('extension/tm')}" />
                                    {if $redirectme}
                                        <input type="hidden" name="RedirectURIAfterPublish" value="{$redirectme}" />
                                    {else}
                                        <input type="hidden" name="RedirectURIAfterPublish" value="{concat("collaboration/item/full/", $collab_item.id)}" />
                                    {/if}
                                </form>
                            </div>
                            {/if}                                                    
                            {*if translator and status uploaded but unconfirmed OR if checker and state undone*}
                            {if or( and( $current_participant.participant_role|eq( 1031 ), 
                                         array( 10 )|contains( $collab_item.data_int3 ) ), 
                                    and( $current_participant.participant_role|eq( 1032 ), 
                                         array( 4 )|contains( $collab_item.data_int3 ) ), 
                                    and( array( 4 )|contains( $tm.status ), 
                                         or($current_participant.participant_role|eq( 1030 ),$current_participant.participant_role|eq( 1032 ) ), 
                                         not(array( 7,8,9,10 )|contains( $collab_item.data_int3 ) ) ) )}
                            <div class="element">
                                <form method="post" action={"content/action"|ezurl()}>
                                    <input type="hidden" name="CollaborationActionCustom" value="custom" />
                                    <input type="hidden" name="CollaborationTypeIdentifier" value="translation" />
                                    <input type="hidden" name="CollaborationItemID" value="{$collab_item.id}" />
                                    <input type="hidden" value="{$translation.locale}" name="ContentObjectLanguageCode" />
                                    <input type="hidden" value="{$object.id}" name="ContentObjectID" />
                                    <input type="hidden" value="{$version_number}" name="ContentObjectVersion" />
                                    <input type="hidden" value="{concat($translation.locale,'/',$object.current_language)}" name="ContentObjectLanguageCode" />                                    
                                    <input type="hidden" name="RedirectIfDiscarded" value="{concat("collaboration/item/full/", $collab_item.id)}" />
                                    {if $redirectme}
                                        <input type="hidden" name="RedirectURIAfterPublish" value="{$redirectme}#nopublish" />
                                    {else}
                                        <input type="hidden" name="RedirectURIAfterPublish" value="{concat("collaboration/item/full/", $collab_item.id)}#nopublish" />
                                    {/if}
                                    <input type="submit" title="{'Edit the contents of this item.'|i18n('extension/tm')}" value="{'Edit'|i18n('extension/tm')}" name="EditButton" class="button">
                                </form>
                            </div>
                            {/if}
                            {if and( $tm.can_approve, $tm.status|eq( 6 ) )}
                                <div class="element">
                                    <form method="post" action={"collaboration/action/"|ezurl}  enctype="multipart/form-data">
                                        <input class="button" type="submit" name="CollaborationAction_Approve" value="{'Approve'|i18n('extension/tm')}" title="{'Approve translation'|i18n('extension/tm')}" />
                                        <input name="CollaborationActionCustom" type="hidden"  value="custom" />
                                        <input name="CollaborationTypeIdentifier" type="hidden" value="translation" />
                                        <input name="CollaborationItemID" type="hidden" value="{$collab_item.id}" />
                                        <input name="ObjectID" type="hidden" value="{$tm.contentobject_id}" />
                                        <input name="VersionID" type="hidden" value="{$tm.contentobject_version}" />
                                        <input name="Target" type="hidden" value="{$tm.language}" /> 
                                        {if $redirectme}
                                            <input type="hidden" name="RedirectURIAfterPublish" value="{$redirectme}" />
                                        {else}
                                            <input type="hidden" name="RedirectURIAfterPublish" value="{concat("collaboration/item/full/", $collab_item.id)}" />
                                        {/if}
                                      </form>
                                </div>
                            {/if}
							
							{if and( $tm.can_approve, or($tm.status|eq( 2 ), $tm.status|eq( 6 ), $tm.status|eq( 10 )) )}
								<div class="element">
									<form method="post" action={"collaboration/action/"|ezurl} enctype="multipart/form-data">
										<input name="CollaborationActionCustom" type="hidden" value="custom" />
										<input name="CollaborationTypeIdentifier" type="hidden" value="translation" />
										<input name="CollaborationItemID" type="hidden" value="{$collab_item.id}" />
										<input name="ObjectID" type="hidden" value="{$tm.contentobject_id}" />
										<input name="VersionID" type="hidden" value="{$tm.contentobject_version}" /> 
										<input name="Target" type="hidden" value="{$tm.language}" />
										<input class="button" type="submit" name="CollaborationAction_Reopen" value="{'Unapprove'|i18n('extension/tm')}" title="{'Unapprove translation'|i18n('extension/tm')}" />
									</form>
								</div>
                            {/if}
                            </div>
                        </td>
                    {if and( $row_count|gt( 1 ), $counter|lt( $row_count ) )}
						</tr>
                    {/if}
                {/if}
            {/foreach}
			{set $row_count = 0}
            </tr>
        {/foreach}
    </table>
    {* DESIGN: Content END *}</div></div></div></div></div></div>
    </div>
    <div class="controlbar">
        {* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
        <div class="block">
            <div class="break"></div>
            <div class="button-right">
                <form method="post" action={"collaboration/action/"|ezurl}  enctype="multipart/form-data">
                    {if and( array(1,2,4)|contains($collab_item.data_int3), $current_participant.participant_role|eq(1030) )}
                        <input type="hidden" name="CollaborationActionCustom" value="custom" />
                        <input type="hidden" name="CollaborationTypeIdentifier" value="translation" />
                        <input type="hidden" name="CollaborationItemID" value="{$collab_item.id}" />
                        <select name="language">
                            {foreach $languages as $key => $language}
                                <option value="{$language.locale}">{$language.name}</option>
                            {/foreach}
                        </select>
                        <input class="button" type="submit" name="CollaborationAction_ConfirmAll" value="{'Confirm all'|i18n('design/admin/collaboration/handler/view/full/ezapprove')}" onclick="return confirmDiscard( 'Are you sure you want to confirm all translations of this language?' );" title="{'Confirm all translations.'|i18n('extension/tm')}" />
                    {/if}
                    {if and( array(6,10)|contains($collab_item.data_int3), $current_participant.participant_role|eq(1032) )}
                        <input type="hidden" name="CollaborationActionCustom" value="custom" />
                        <input type="hidden" name="CollaborationTypeIdentifier" value="translation" />
                        <input type="hidden" name="CollaborationItemID" value="{$collab_item.id}" />
                        <select name="language">
                            {foreach $languages as $key => $language}
                                <option value="{$language.locale}">{$language.name}</option>
                            {/foreach}
                        </select>
                        <input class="button" type="submit" name="CollaborationAction_ApproveAll" value="{'Approve all'|i18n('design/admin/collaboration/handler/view/full/ezapprove')}" onclick="return confirmDiscard( 'Are you sure you want to approve all translations of this language?' );" title="{'Confirm all translations.'|i18n('extension/tm')}" />
                    {/if}
                </form>
            </div>
            <div class="break"></div>
        </div>
        {* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>
{/if}
