{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="message-error">
<h2>{"Zend Optimizer not installed"|i18n("design/standard/error/kernel")}</h2>
<p>{"An extension was encoded. In order to run it, please install the freely available Zend Optimizer, version 2.1.0 or later."|i18n("design/standard/error/kernel")}</p>
<p><a href="http://www.zend.com/store/products/zend-optimizer.php">{"Download Zend Optimizer"|i18n("design/standard/error/kernel")}</a></p>

<p>{"Other options"|i18n("design/standard/error/kernel")}</a></p>
<ul>
    <li>{"Buy the required licence in order to receive unencoded sources."|i18n("design/standard/error/kernel")}</li>
    <li>{"Request a free demo tour on another system."|i18n("design/standard/error/kernel")}</li>
</ul>
</div>


{section show=$embed_content}

{$embed_content}
{/section}
