{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{set-block scope=root variable=subject}{'[%sitename] Completed translation collaboration %objectname'
                                        |i18n( "extension/tm",,
                                               hash( '%sitename', ezini( "SiteSettings", "SiteURL" ),
                                                     '%objectname', concat( '#',$collaboration_item.id )|wash ) )}{/set-block}
{'This e-mail is to inform you that content objects are translated and confirmed.'
 |i18n( 'extension/tm',,
        hash( '%sitename', ezini( "SiteSettings", "SiteURL" ),
              '%objectname', $objectversion.version_name|wash ) )}


{'This collaboration is waiting your approval.'
 |i18n( 'extension/tm',,
        hash( '%sitename', ezini( "SiteSettings", "SiteURL" ),
              '%objectname', $objectversion.version_name|wash ) )}


{'The translation process can viewed by using the URL below.'
 |i18n( 'extension/tm',,
        hash( '%sitename', ezini( "SiteSettings", "SiteURL" ),
              '%objectname', $objectversion.version_name|wash ) )}
http://{ezini( "SiteSettings", "SiteURL" )}{concat( "collaboration/item/full/", $collaboration_item.id )|ezurl( no )}

{"If you do not wish to continue receiving these notifications,
change your settings at:"|i18n( 'design/standard/notification' )}
http://{ezini( "SiteSettings", "SiteURL" )}{concat( "notification/settings/" )|ezurl( no )}

--
{"%sitename notification system"
 |i18n( 'extension/tm',,
        hash( '%sitename', ezini( "SiteSettings", "SiteURL" )  ) )}