{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let approval_content=$collaboration_item.content
     objectversion=fetch( content, version,
                          hash( object_id, $approval_content.content_object_id,
                                version_id, $approval_content.content_object_version ) )}
{set-block scope=root variable=subject}{'[%sitename] "%objectname" awaits translation'
                                        |i18n( "extension/tm",,
                                               hash( '%sitename', ezini( "SiteSettings", "SiteURL" ),
                                                     '%objectname', $objectversion.version_name|wash ) )}{/set-block}
{'This e-mail is to inform you that "%objectname" awaits approval at %sitename before it is published.
If you wish to send comments to the translators or view the status use the URL below.'
 |i18n( 'extension/tm',,
        hash( '%sitename', $collaboration_item.data_text2,
              '%objectname', $objectversion.version_name|wash ) )}
http://{ezini( "SiteSettings", "SiteURL" )}{concat( "collaboration/item/full/", $collaboration_item.id )|ezurl( no )}

{"If you do not wish to continue receiving these notifications,
change your settings at:"|i18n( 'extension/tm' )}
http://{ezini( "SiteSettings", "SiteURL" )}{concat( "notification/settings/" )|ezurl( no )}

--
{"%sitename notification system"
 |i18n( 'extension/tm',,
        hash( '%sitename', ezini( "SiteSettings", "SiteURL" ) ) )}
{/let}