{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $name=concat( '<i>','Translation collaboration', ' #', $item.id,'</i>')}
{def $item_text=''}
{def $current_participant=fetch("collaboration","participant",hash("item_id",$item.id))}
{if $item.is_creator}
  {switch match=$item.data_int3}
  {case in=array(1,4)}
   {def $item_text="%1 awaits translation by translators"|i18n('design/standard/collaboration',,array($name))}
  {/case}
  {case in=array( 6 )}
   {def $item_text="%1 awaits approval"|i18n('design/standard/collaboration',,array($name))}
  {/case}
  {case match=array(8,10)}
   {def $item_text="%1 was approved for publishing"|i18n('design/standard/collaboration',,array($name))}
  {/case}
  {case in=array(2,3)}
   {def $item_text="%1 was not approved for publishing"|i18n('design/standard/collaboration',,array($name))}
  {/case}
  {/switch}
{/if}
{if $current_participant.participant_role|eq(1030)}
  {switch match=$item.data_int3}
  {case match=1}
   {def $item_text="%1 awaits your translation"|i18n('design/standard/collaboration',,array($name))}
  {/case}
  {case in=array(2,3)}
   {def $item_text="%1 had not approved translation"|i18n('design/standard/collaboration',,array($name))}
  {/case}
  {case match=6}
   {def $item_text="%1 awaits approval"|i18n('design/standard/collaboration',,array($name))}
  {/case}
  {/switch}
{/if}
{if $current_participant.participant_role|eq(1032)}
  {switch match=$item.data_int3}
  {case match=6}
   {def $item_text="%1 awaits your approval"|i18n('design/standard/collaboration',,array($name))}
  {/case}
  {/switch}
{/if}
  {switch match=$item.data_int3}
  {case match=8}
   {def $item_text="%1 was approved for publishing"|i18n('design/standard/collaboration',,array($name))}
  {/case}
  {case match=10}
   {def $item_text="%1 is waiting for publishing"|i18n('design/standard/collaboration',,array($name))}
  {/case}
  {case match=9}
   {def $item_text="%1 was rejected"|i18n('design/standard/collaboration',,array($name))}
  {/case}
  {/switch}
{def $languages = $collab_item.content.languages}

<p class="{$:item_class} translation-status-{$item.status}">
<a class="{$:item_class}" href={concat("collaboration/item/full/",$:item.id)|ezurl}>{$item_text}</a>
Languages: 
{foreach $item.content.languages as $language}
{$language.name}
{delimiter},{/delimiter}
{/foreach}
</p>
